version: '3.4'

volumes:
  shared_data:

services:
  web:
    image: smgirls/web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - shared_data:/usr/src/app/share
    ports:
      - 7000:7000
  box1:
    image: smgirls/simul
    build:
      context: .
      dockerfile: Dockerfile-simul
    volumes:
      - shared_data:/usr/src/app/share
    environment:
      - START_ROW=1
  box2:
    image: smgirls/simul
    build:
      context: .
      dockerfile: Dockerfile-simul
    volumes:
      - shared_data:/usr/src/app/share
    environment:
      - START_ROW=11
  box3:
    image: smgirls/simul
    build:
      context: .
      dockerfile: Dockerfile-simul
    volumes:
      - shared_data:/usr/src/app/share
    environment:
      - START_ROW=21
  box4:
    image: smgirls/simul
    build:
      context: .
      dockerfile: Dockerfile-simul
    volumes:
     - shared_data:/usr/src/app/share
    environment:
      - START_ROW=31
  box5:
    image: smgirls/simul
    build:
      context: .
      dockerfile: Dockerfile-simul
    volumes:
      - shared_data:/usr/src/app/share
    environment:
      - START_ROW=41
