FROM python:3.10.11-slim

WORKDIR /usr/src/app

COPY Dockerfile-simul .
COPY requirements-simul.txt .
COPY visualize.py .

ENV START_ROW 1
# RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install -r requirements-simul.txt

CMD python3 visualize.py