version: '3.4'

services:
  box1:
    image: smgirls/simulator
    environment:
      - START_ROW=1
    ports:
      - "5000:5000"
  box2:
    image: smgirls/simulator
    environment:
      - START_ROW=11
    ports:
      - "5001:5000"
  box3:
    image: smgirls/simulator
    environment:
      - START_ROW=21
    ports:
      - "5002:5000"
  box4:
    image: smgirls/simulator
    environment:
      - START_ROW=31
    ports:
      - "5003:5000"
