apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: smgirls/web
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/share
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc

---

# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: box1
# spec:
#   template:
#     metadata:
#       labels:
#         app: box1
#     spec:
#       containers:
#         - name: box1
#           image: smgirls/simul
#           imagePullPolicy: Never
#           env:
#             - name: START_ROW
#               value: "1"
#           volumeMounts:
#             - name: shared-data
#               mountPath: /usr/src/app/share
#       restartPolicy: Never
#       volumes:
#         - name: shared-data
#           persistentVolumeClaim:
#             claimName: shared-data-pvc

# ---

# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: box2
# spec:
#   template:
#     metadata:
#       labels:
#         app: box2
#     spec:
#       containers:
#         - name: box2
#           image: smgirls/simul
#           imagePullPolicy: Never
#           env:
#             - name: START_ROW
#               value: "11"
#           volumeMounts:
#             - name: shared-data
#               mountPath: /usr/src/app/share
#       restartPolicy: Never
#       volumes:
#         - name: shared-data
#           persistentVolumeClaim:
#             claimName: shared-data-pvc
