#!/bin/bash

# app.py 실행 (포트 7000)
export FLASK_APP=app
export FLASK_RUN_PORT=7000
flask run &

# visualize_func.py 실행 (포트 7001)
export FLASK_APP=visualize_func
export FLASK_RUN_PORT=7001
flask run &
